### ISSUE TITLE
build bvs error 

### ISSUE THREAD

**Issue by gispda** [swehrwein/vsbmm#1]
Ubuntu 16.04
all component is installed.
build trackseg is okay.
build bvs error.

In file included from /home/gisphd/project/vsbmm/bvs/../common/TrackTable-inl.h:3:0,
                 from /home/gisphd/project/vsbmm/bvs/BilateralSegment.cpp:13:
/home/gisphd/project/vsbmm/bvs/../common/FileIo.h: In function ‘T fread(FILE*) [with T = bool; FILE = _IO_FILE]’:
/home/gisphd/project/vsbmm/bvs/../common/FileIo.h:11:3: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&temp, sizeof(T), 1, fin);
   ^
In file included from /home/gisphd/project/vsbmm/bvs/BilateralSegment.cpp:13:0:
/home/gisphd/project/vsbmm/bvs/../common/TrackTable-inl.h: In member function ‘void Track<ObsType, TrackExtraType>::deserialize(FILE*) [with ObsType = Observation2d; TrackExtraType = RansacData; FILE = _IO_FILE]’:
/home/gisphd/project/vsbmm/bvs/../common/TrackTable-inl.h:64:5: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&obs_.atAbs(0), sizeof(ObsType), size, fin);
     ^
In file included from /home/gisphd/project/vsbmm/bvs/BilateralSegment.cpp:14:0:
/home/gisphd/project/vsbmm/bvs/../common/RansacData.h: In member function ‘void RansacData::deserialize(FILE*)’:
/home/gisphd/project/vsbmm/bvs/../common/RansacData.h:34:48: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&inlWts[0], sizeof(float), size, fin);
                                                ^
/home/gisphd/project/vsbmm/bvs/../common/RansacData.h:40:54: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&frameError[off], sizeof(float), size, fin);
                                                      ^
In file included from /home/gisphd/project/vsbmm/bvs/../common/TrackTable-inl.h:3:0,
                 from /home/gisphd/project/vsbmm/bvs/BilateralSegment.cpp:13:
/home/gisphd/project/vsbmm/bvs/../common/FileIo.h: In function ‘T fread(FILE*) [with T = int; FILE = _IO_FILE]’:
/home/gisphd/project/vsbmm/bvs/../common/FileIo.h:11:3: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&temp, sizeof(T), 1, fin);
   ^
/home/gisphd/project/vsbmm/bvs/../common/FileIo.h: In function ‘T fread(FILE*) [with T = long unsigned int; FILE = _IO_FILE]’:
/home/gisphd/project/vsbmm/bvs/../common/FileIo.h:11:3: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp: In instantiation of ‘flowtype Graph<captype, tcaptype, flowtype>::maxflow(bool, Block<int>*) [with captype = int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:12:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:484:84: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 eration == 0 && reuse_trees) { if (error_function) (*error_function)("reuse_tre
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:485:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 hanged_list && !reuse_trees) { if (error_function) (*error_function)("changed_l
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp: In instantiation of ‘flowtype Graph<captype, tcaptype, flowtype>::maxflow(bool, Block<int>*) [with captype = short int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:13:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:484:84: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 eration == 0 && reuse_trees) { if (error_function) (*error_function)("reuse_tre
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:485:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 hanged_list && !reuse_trees) { if (error_function) (*error_function)("changed_l
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp: In instantiation of ‘flowtype Graph<captype, tcaptype, flowtype>::maxflow(bool, Block<int>*) [with captype = float; tcaptype = float; flowtype = float]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:14:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:484:84: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 eration == 0 && reuse_trees) { if (error_function) (*error_function)("reuse_tre
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:485:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 hanged_list && !reuse_trees) { if (error_function) (*error_function)("changed_l
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp: In instantiation of ‘flowtype Graph<captype, tcaptype, flowtype>::maxflow(bool, Block<int>*) [with captype = double; tcaptype = double; flowtype = double]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:15:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:484:84: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 eration == 0 && reuse_trees) { if (error_function) (*error_function)("reuse_tre
                                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:485:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 hanged_list && !reuse_trees) { if (error_function) (*error_function)("changed_l
                                                                     ^
In file included from /home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.h:43:0,
                 from /home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:5:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h: In instantiation of ‘Type* DBlock<Type>::New() [with Type = Graph<int, int, int>::nodeptr]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:84:5:   required from ‘void Graph<captype, tcaptype, flowtype>::set_orphan_front(Graph<captype, tcaptype, flowtype>::node*) [with captype = int; tcaptype = int; flowtype = int]’
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:12:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h:223:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
    if (!first) { if (error_function) (*error_function)("Not enough memory!"); e
                                                       ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h: In instantiation of ‘Type* Block<Type>::New(int) [with Type = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:110:35:   required from ‘void Graph<captype, tcaptype, flowtype>::add_to_changed_list(Graph<captype, tcaptype, flowtype>::node*) [with captype = int; tcaptype = int; flowtype = int]’
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:12:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h:124:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     if (!next) { if (error_function) (*error_function)("Not enough memory!"); e
                                                       ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h: In instantiation of ‘Type* DBlock<Type>::New() [with Type = Graph<short int, int, int>::nodeptr]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:84:5:   required from ‘void Graph<captype, tcaptype, flowtype>::set_orphan_front(Graph<captype, tcaptype, flowtype>::node*) [with captype = short int; tcaptype = int; flowtype = int]’
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:13:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h:223:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
    if (!first) { if (error_function) (*error_function)("Not enough memory!"); e
                                                       ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h: In instantiation of ‘Type* DBlock<Type>::New() [with Type = Graph<float, float, float>::nodeptr]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:84:5:   required from ‘void Graph<captype, tcaptype, flowtype>::set_orphan_front(Graph<captype, tcaptype, flowtype>::node*) [with captype = float; tcaptype = float; flowtype = float]’
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:14:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h:223:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h: In instantiation of ‘Type* DBlock<Type>::New() [with Type = Graph<double, double, double>::nodeptr]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/maxflow.cpp:84:5:   required from ‘void Graph<captype, tcaptype, flowtype>::set_orphan_front(Graph<captype, tcaptype, flowtype>::node*) [with captype = double; tcaptype = double; flowtype = double]’
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:15:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/block.h:223:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘Graph<captype, tcaptype, flowtype>::Graph(int, int, void (*)(char*)) [with captype = int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:12:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:21:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes || !arcs) { if (error_function) (*error_function)("Not enough memor
                                                              ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_nodes(int) [with captype = int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:12:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:70:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes) { if (error_function) (*error_function)("Not enough memory!"); exi
                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_arcs() [with captype = int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:12:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:94:52: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!arcs) { if (error_function) (*error_function)("Not enough memory!"); exit
                                                    ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘Graph<captype, tcaptype, flowtype>::Graph(int, int, void (*)(char*)) [with captype = short int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:13:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:21:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes || !arcs) { if (error_function) (*error_function)("Not enough memor
                                                              ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_nodes(int) [with captype = short int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:13:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:70:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes) { if (error_function) (*error_function)("Not enough memory!"); exi
                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_arcs() [with captype = short int; tcaptype = int; flowtype = int]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:13:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:94:52: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!arcs) { if (error_function) (*error_function)("Not enough memory!"); exit
                                                    ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘Graph<captype, tcaptype, flowtype>::Graph(int, int, void (*)(char*)) [with captype = float; tcaptype = float; flowtype = float]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:14:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:21:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes || !arcs) { if (error_function) (*error_function)("Not enough memor
                                                              ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_nodes(int) [with captype = float; tcaptype = float; flowtype = float]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:14:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:70:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes) { if (error_function) (*error_function)("Not enough memory!"); exi
                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_arcs() [with captype = float; tcaptype = float; flowtype = float]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:14:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:94:52: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!arcs) { if (error_function) (*error_function)("Not enough memory!"); exit
                                                    ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘Graph<captype, tcaptype, flowtype>::Graph(int, int, void (*)(char*)) [with captype = double; tcaptype = double; flowtype = double]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:15:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:21:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes || !arcs) { if (error_function) (*error_function)("Not enough memor
                                                              ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_nodes(int) [with captype = double; tcaptype = double; flowtype = double]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:15:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:70:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!nodes) { if (error_function) (*error_function)("Not enough memory!"); exi
                                                     ^
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp: In instantiation of ‘void Graph<captype, tcaptype, flowtype>::reallocate_arcs() [with captype = double; tcaptype = double; flowtype = double]’:
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/instances.inc:15:16:   required from here
/home/gisphd/project/vsbmm/bvs/maxflow-v3.01/graph.cpp:94:52: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  if (!arcs) { if (error_function) (*error_function)("Not enough memory!"); exit
                                                    ^
CMakeFiles/bseg.dir/BilateralSegment.cpp.o: In function `graphCut(Grid<cv::Vec<float, 4>, 6>&)':
BilateralSegment.cpp:(.text+0x1bd7): undefined reference to `Graph<float, float, double>::Graph(int, int, void (*)(char*))'
BilateralSegment.cpp:(.text+0x23b9): undefined reference to `Graph<float, float, double>::reallocate_arcs()'
BilateralSegment.cpp:(.text+0x247d): undefined reference to `Graph<float, float, double>::~Graph()'
BilateralSegment.cpp:(.text+0x2507): undefined reference to `Graph<float, float, double>::maxflow(bool, Block<int>*)'
BilateralSegment.cpp:(.text+0x2699): undefined reference to `Graph<float, float, double>::~Graph()'
BilateralSegment.cpp:(.text+0x274f): undefined reference to `Graph<float, float, double>::reallocate_nodes(int)'
collect2: error: ld returned 1 exit status
make[2]: *** [bseg] Error 1
make[1]: *** [CMakeFiles/bseg.dir/all] Error 2
make: *** [all] Error 2

**Comment by swehrwein** [comment]
Did you add the typedef in graphcut library as described in the readme?

Relevant bit reproduced here:
```
Note: I use a custom instantiation of the Graph template from maxflow
that isn't included in instances.inc (thanks to Yucheng Lu for pointing
this out). To get the bvs code to build, you'll need to add the
following line to maxflow-v3.01/instances.inc:
template class Graph<float, float, double>;
```
